"""init

Revision ID: 026b2fbec85c
Revises: 
Create Date: 2025-11-09 23:49:35.589739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '026b2fbec85c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skins',
    sa.Column('market_hash_name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('weapon', sa.String(), nullable=True),
    sa.Column('wear', sa.String(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('stattrak', sa.Boolean(), nullable=True),
    sa.Column('souvenir', sa.Boolean(), nullable=True),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_last_1_day', sa.Float(), nullable=True),
    sa.Column('price_last_7_day', sa.Float(), nullable=True),
    sa.Column('price_last_30_day', sa.Float(), nullable=True),
    sa.Column('price_last_365_day', sa.Float(), nullable=True),
    sa.Column('price_last_all_day', sa.Float(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('last_price_update', sa.DateTime(), nullable=True),
    sa.Column('sell_by_last_update', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('market_hash_name')
    )
    op.create_index(op.f('ix_skins_category'), 'skins', ['category'], unique=False)
    op.create_index(op.f('ix_skins_rarity'), 'skins', ['rarity'], unique=False)
    op.create_index(op.f('ix_skins_short_name'), 'skins', ['short_name'], unique=False)
    op.create_index(op.f('ix_skins_weapon'), 'skins', ['weapon'], unique=False)
    op.create_index(op.f('ix_skins_wear'), 'skins', ['wear'], unique=False)
    op.create_table('users',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('steam_id', sa.BigInteger(), nullable=False),
    sa.Column('steam_name', sa.String(), nullable=False),
    sa.Column('steam_avatar', sa.String(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('notify', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_users_steam_id'), 'users', ['steam_id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.create_table('skins_collections',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('market_hash_name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('collection', sa.String(), nullable=False),
    sa.Column('image_link', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['market_hash_name'], ['skins.market_hash_name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_skins_collections_collection'), 'skins_collections', ['collection'], unique=False)
    op.create_index(op.f('ix_skins_collections_market_hash_name'), 'skins_collections', ['market_hash_name'], unique=False)
    op.create_table('skins_price_history',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('market_hash_name', sa.String(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_hash_name'], ['skins.market_hash_name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_skins_price_history_market_hash_name'), 'skins_price_history', ['market_hash_name'], unique=False)
    op.create_index(op.f('ix_skins_price_history_timestamp'), 'skins_price_history', ['timestamp'], unique=False)
    op.create_table('users_likes_skins',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('market_hash_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['market_hash_name'], ['skins.market_hash_name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_users_likes_skins_market_hash_name'), 'users_likes_skins', ['market_hash_name'], unique=False)
    op.create_index(op.f('ix_users_likes_skins_user_uuid'), 'users_likes_skins', ['user_uuid'], unique=False)
    op.create_table('users_notifies',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('notify_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_users_notifies_created_at'), 'users_notifies', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_notifies_notify_type'), 'users_notifies', ['notify_type'], unique=False)
    op.create_index(op.f('ix_users_notifies_user_uuid'), 'users_notifies', ['user_uuid'], unique=False)
    op.create_table('users_portfolio',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('market_hash_name', sa.String(), nullable=False),
    sa.Column('benefit', sa.Float(), nullable=False),
    sa.Column('notify_percent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['market_hash_name'], ['skins.market_hash_name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_users_portfolio_market_hash_name'), 'users_portfolio', ['market_hash_name'], unique=False)
    op.create_index(op.f('ix_users_portfolio_user_uuid'), 'users_portfolio', ['user_uuid'], unique=False)
    op.create_table('portfolio_skins_transactions',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('portfolio_skin_uuid', sa.UUID(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('buy_price', sa.Float(), nullable=False),
    sa.Column('when_buy', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_skin_uuid'], ['users_portfolio.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_portfolio_skins_transactions_portfolio_skin_uuid'), 'portfolio_skins_transactions', ['portfolio_skin_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_skins_transactions_portfolio_skin_uuid'), table_name='portfolio_skins_transactions')
    op.drop_table('portfolio_skins_transactions')
    op.drop_index(op.f('ix_users_portfolio_user_uuid'), table_name='users_portfolio')
    op.drop_index(op.f('ix_users_portfolio_market_hash_name'), table_name='users_portfolio')
    op.drop_table('users_portfolio')
    op.drop_index(op.f('ix_users_notifies_user_uuid'), table_name='users_notifies')
    op.drop_index(op.f('ix_users_notifies_notify_type'), table_name='users_notifies')
    op.drop_index(op.f('ix_users_notifies_created_at'), table_name='users_notifies')
    op.drop_table('users_notifies')
    op.drop_index(op.f('ix_users_likes_skins_user_uuid'), table_name='users_likes_skins')
    op.drop_index(op.f('ix_users_likes_skins_market_hash_name'), table_name='users_likes_skins')
    op.drop_table('users_likes_skins')
    op.drop_index(op.f('ix_skins_price_history_timestamp'), table_name='skins_price_history')
    op.drop_index(op.f('ix_skins_price_history_market_hash_name'), table_name='skins_price_history')
    op.drop_table('skins_price_history')
    op.drop_index(op.f('ix_skins_collections_market_hash_name'), table_name='skins_collections')
    op.drop_index(op.f('ix_skins_collections_collection'), table_name='skins_collections')
    op.drop_table('skins_collections')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_steam_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skins_wear'), table_name='skins')
    op.drop_index(op.f('ix_skins_weapon'), table_name='skins')
    op.drop_index(op.f('ix_skins_short_name'), table_name='skins')
    op.drop_index(op.f('ix_skins_rarity'), table_name='skins')
    op.drop_index(op.f('ix_skins_category'), table_name='skins')
    op.drop_table('skins')
    # ### end Alembic commands ###
