"""enum to string

Revision ID: 04cb13552567
Revises: 3a9df9209988
Create Date: 2025-09-07 11:54:55.916255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04cb13552567'
down_revision: Union[str, Sequence[str], None] = '3a9df9209988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skins_price_info', 'update_mode',
               existing_type=postgresql.ENUM('HIGH', 'MEDIUM_WELL', 'MEDIUM', 'LOW', name='update_mode'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users_notify', 'notify_type',
               existing_type=postgresql.ENUM('INFO', 'SKIN', name='notifytype'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_notify', 'notify_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('INFO', 'SKIN', name='notifytype'),
               existing_nullable=False)
    op.alter_column('skins_price_info', 'update_mode',
               existing_type=sa.String(),
               type_=postgresql.ENUM('HIGH', 'MEDIUM_WELL', 'MEDIUM', 'LOW', name='update_mode'),
               existing_nullable=False)
    # ### end Alembic commands ###
