"""image_link to skins_wears and category, weapon to skins

Revision ID: 1304089e810a
Revises: 288279e179e2
Create Date: 2025-11-23 01:26:50.185945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1304089e810a'
down_revision: Union[str, Sequence[str], None] = '288279e179e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins', sa.Column('category', sa.String(), nullable=False))
    op.add_column('skins', sa.Column('weapon', sa.String(), nullable=True))
    op.create_index(op.f('ix_skins_category'), 'skins', ['category'], unique=False)
    op.create_index(op.f('ix_skins_weapon'), 'skins', ['weapon'], unique=False)
    op.drop_column('skins', 'image_link')
    op.add_column('skins_wears', sa.Column('image_link', sa.String(), nullable=False))
    op.drop_index(op.f('ix_skins_wears_category'), table_name='skins_wears')
    op.drop_index(op.f('ix_skins_wears_weapon'), table_name='skins_wears')
    op.drop_column('skins_wears', 'weapon')
    op.drop_column('skins_wears', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins_wears', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('skins_wears', sa.Column('weapon', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_skins_wears_weapon'), 'skins_wears', ['weapon'], unique=False)
    op.create_index(op.f('ix_skins_wears_category'), 'skins_wears', ['category'], unique=False)
    op.drop_column('skins_wears', 'image_link')
    op.add_column('skins', sa.Column('image_link', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_skins_weapon'), table_name='skins')
    op.drop_index(op.f('ix_skins_category'), table_name='skins')
    op.drop_column('skins', 'weapon')
    op.drop_column('skins', 'category')
    # ### end Alembic commands ###
