"""add comment in skin portfolio transation

Revision ID: 1cca0ce84865
Revises: c8c3455fce1f
Create Date: 2025-11-15 01:52:28.346893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cca0ce84865'
down_revision: Union[str, Sequence[str], None] = 'c8c3455fce1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_skins_transactions', sa.Column('comment', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_skins_transactions', 'comment')
    # ### end Alembic commands ###
