"""new indexes

Revision ID: 27f5cf92fce7
Revises: e05bf75278f0
Create Date: 2025-08-03 18:47:42.728637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27f5cf92fce7'
down_revision: Union[str, Sequence[str], None] = 'e05bf75278f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_skin_name', 'skins_price_info', ['skin_name'], unique=False)
    op.create_index('idx_update_mode', 'skins_price_info', ['update_mode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_update_mode', table_name='skins_price_info')
    op.drop_index('idx_skin_name', table_name='skins_price_info')
    # ### end Alembic commands ###
