"""init

Revision ID: 398c1c883c70
Revises: 
Create Date: 2025-06-21 17:00:49.720012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '398c1c883c70'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skins',
    sa.Column('skin_id', sa.BigInteger(), nullable=False),
    sa.Column('skin_name', sa.String(), nullable=False),
    sa.Column('skin_avatar', sa.String(), nullable=False),
    sa.Column('skin_price', sa.Float(), nullable=False),
    sa.Column('rarity', sa.String(), nullable=False),
    sa.Column('collection', sa.String(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('price_last_1_day', sa.Float(), nullable=True),
    sa.Column('price_last_7_days', sa.Float(), nullable=True),
    sa.Column('price_last_30_days', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('skin_id'),
    sa.UniqueConstraint('skin_id')
    )
    op.create_index('idx_collection', 'skins', ['collection'], unique=False)
    op.create_index('idx_item_type', 'skins', ['item_type'], unique=False)
    op.create_index('idx_rarity', 'skins', ['rarity'], unique=False)
    op.create_index('idx_skin_name', 'skins', ['skin_name'], unique=False)
    op.create_table('skins_price_history',
    sa.Column('skin_id', sa.BigInteger(), nullable=False),
    sa.Column('skin_name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('skin_id'),
    sa.UniqueConstraint('skin_id')
    )
    op.create_index('idx_skin_history_name', 'skins_price_history', ['skin_name'], unique=False)
    op.create_index('idx_skin_history_timestamp', 'skins_price_history', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('steam_id', sa.BigInteger(), nullable=False),
    sa.Column('steam_name', sa.String(), nullable=False),
    sa.Column('steam_avatar', sa.String(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_steam_id', 'users', ['steam_id'], unique=False)
    op.create_index('idx_telegram_id', 'users', ['telegram_id'], unique=False)
    op.create_table('assotiation',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['skins.skin_id'], ),
    sa.ForeignKeyConstraint(['uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid', 'id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assotiation')
    op.drop_index('idx_telegram_id', table_name='users')
    op.drop_index('idx_steam_id', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_skin_history_timestamp', table_name='skins_price_history')
    op.drop_index('idx_skin_history_name', table_name='skins_price_history')
    op.drop_table('skins_price_history')
    op.drop_index('idx_skin_name', table_name='skins')
    op.drop_index('idx_rarity', table_name='skins')
    op.drop_index('idx_item_type', table_name='skins')
    op.drop_index('idx_collection', table_name='skins')
    op.drop_table('skins')
    # ### end Alembic commands ###
