""".

Revision ID: 3a9df9209988
Revises: 27f5cf92fce7
Create Date: 2025-08-10 12:49:26.263958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a9df9209988'
down_revision: Union[str, Sequence[str], None] = '27f5cf92fce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE notifytype AS ENUM ('INFO', 'SKIN')")
    
    op.alter_column('skins_price_info', 'last_update',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
            )
    op.drop_column('skins_price_info', 'uuid')
    op.add_column('users_notify', sa.Column('notify_type', sa.Enum('INFO', 'SKIN', name='notifytype', create_type=False), nullable=False))
    op.drop_column('users_skins', 'quantity')
    op.drop_column('users_skins', 'buy_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_skins', sa.Column('buy_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('users_skins', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users_notify', 'notify_type')
    op.add_column('skins_price_info', sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.alter_column('skins_price_info', 'last_update',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
