"""enum in skins

Revision ID: 3da559247ee2
Revises: a1bca6940bea
Create Date: 2025-07-08 17:27:19.474047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da559247ee2'
down_revision: Union[str, Sequence[str], None] = 'a1bca6940bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE updatemode AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'MEDIUM_WELL')")
    op.add_column('skins', sa.Column('update_mode', sa.Enum('HIGH', 'MEDIUM_WELL', 'MEDIUM', 'LOW', name='updatemode')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skins', 'update_mode')
    # ### end Alembic commands ###
