"""image to image_link in skins

Revision ID: 3e71093959c1
Revises: c33cf4b511f7
Create Date: 2025-11-10 15:45:39.565850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e71093959c1'
down_revision: Union[str, Sequence[str], None] = 'c33cf4b511f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins', sa.Column('image_link', sa.String(), nullable=False))
    op.drop_column('skins', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('skins', 'image_link')
    # ### end Alembic commands ###
