"""change columns namein skins

Revision ID: 5029a8d880f1
Revises: 8c0fa85c83e9
Create Date: 2025-07-04 13:07:33.318649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5029a8d880f1'
down_revision: Union[str, Sequence[str], None] = '8c0fa85c83e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins', sa.Column('price_last_30_day', sa.Float(), nullable=True))
    op.add_column('skins', sa.Column('price_last_365_day', sa.Float(), nullable=True))
    op.drop_column('skins', 'price_last_30_days')
    op.drop_column('skins', 'price_last_7_days')
    op.create_index('idx_skin_history_id', 'skins_price_history', ['skin_id'], unique=False)
    op.create_unique_constraint(None, 'users', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('idx_skin_history_id', table_name='skins_price_history')
    op.add_column('skins', sa.Column('price_last_7_days', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('skins', sa.Column('price_last_30_days', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('skins', 'price_last_365_day')
    op.drop_column('skins', 'price_last_30_day')
    # ### end Alembic commands ###
