"""new tables

Revision ID: 82bc74b7e842
Revises: 
Create Date: 2025-08-02 23:59:22.476168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82bc74b7e842'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skins',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('steam_id', sa.BigInteger(), nullable=False),
    sa.Column('steam_name', sa.String(), nullable=False),
    sa.Column('steam_avatar', sa.String(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(), nullable=True),
    sa.Column('skin_percent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_steam_id', 'users', ['steam_id'], unique=False)
    op.create_index('idx_telegram_id', 'users', ['telegram_id'], unique=False)
    op.create_table('skins_price_history',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('skin_name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skin_name'], ['skins.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_skin_history_name', 'skins_price_history', ['skin_name'], unique=False)
    op.create_index('idx_skin_history_timestamp', 'skins_price_history', ['timestamp'], unique=False)
    op.create_table('skins_price_info',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('skin_name', sa.String(), nullable=False),
    sa.Column('update_mode', sa.Enum('HIGH', 'MEDIUM_WELL', 'MEDIUM', 'LOW', name='update_mode'), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_last_1_day', sa.Float(), nullable=True),
    sa.Column('price_last_30_day', sa.Float(), nullable=True),
    sa.Column('price_last_365_day', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['skin_name'], ['skins.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('users_notify',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_notify_user_uuid', 'users_notify', ['user_uuid'], unique=False)
    op.create_table('users_skins',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('skin_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('buy_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['skin_name'], ['skins.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_portfolio_skin_name', 'users_skins', ['skin_name'], unique=False)
    op.create_index('idx_portfolio_user_uuid', 'users_skins', ['user_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_portfolio_user_uuid', table_name='users_skins')
    op.drop_index('idx_portfolio_skin_name', table_name='users_skins')
    op.drop_table('users_skins')
    op.drop_index('idx_notify_user_uuid', table_name='users_notify')
    op.drop_table('users_notify')
    op.drop_table('skins_price_info')
    op.drop_index('idx_skin_history_timestamp', table_name='skins_price_history')
    op.drop_index('idx_skin_history_name', table_name='skins_price_history')
    op.drop_table('skins_price_history')
    op.drop_index('idx_telegram_id', table_name='users')
    op.drop_index('idx_steam_id', table_name='users')
    op.drop_table('users')
    op.drop_table('skins')
    # ### end Alembic commands ###
