"""add skin_percent in users

Revision ID: 9d23b07a005f
Revises: 3da559247ee2
Create Date: 2025-07-09 15:13:42.020731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d23b07a005f'
down_revision: Union[str, Sequence[str], None] = '3da559247ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('users', sa.Column('skin_percent', sa.Integer(), default=10))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'skin_percent')
    # ### end Alembic commands ###
