"""add is_collection in skins_collections

Revision ID: a02d227c7291
Revises: d37a71f836e6
Create Date: 2025-11-12 12:04:42.637499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a02d227c7291'
down_revision: Union[str, Sequence[str], None] = 'd37a71f836e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins_collections', sa.Column('is_collection', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skins_collections', 'is_collection')
    # ### end Alembic commands ###
