"""add short_name in users_likes_skins, instead market_hash_name in skins_collections - short_name, primary_join in skins by field collections

Revision ID: c33cf4b511f7
Revises: 026b2fbec85c
Create Date: 2025-11-10 02:00:36.404692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c33cf4b511f7'
down_revision: Union[str, Sequence[str], None] = '026b2fbec85c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skins_collections_market_hash_name'), table_name='skins_collections')
    op.drop_constraint(op.f('skins_collections_market_hash_name_fkey'), 'skins_collections', type_='foreignkey')
    op.drop_column('skins_collections', 'market_hash_name')
    op.add_column('users_likes_skins', sa.Column('short_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_likes_skins', 'short_name')
    op.add_column('skins_collections', sa.Column('market_hash_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('skins_collections_market_hash_name_fkey'), 'skins_collections', 'skins', ['market_hash_name'], ['market_hash_name'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index(op.f('ix_skins_collections_market_hash_name'), 'skins_collections', ['market_hash_name'], unique=False)
    # ### end Alembic commands ###
