"""add is_rare in skins_collections

Revision ID: c8c3455fce1f
Revises: ea42d28da949
Create Date: 2025-11-12 12:27:55.686124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8c3455fce1f'
down_revision: Union[str, Sequence[str], None] = 'ea42d28da949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins_collections', sa.Column('is_rare', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skins_collections', 'is_rare')
    # ### end Alembic commands ###
