"""short_name to market_hash_name in skins_collections

Revision ID: d37a71f836e6
Revises: 3e71093959c1
Create Date: 2025-11-10 18:50:36.362634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd37a71f836e6'
down_revision: Union[str, Sequence[str], None] = '3e71093959c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins_collections', sa.Column('market_hash_name', sa.String(), nullable=False))
    op.create_index(op.f('ix_skins_collections_market_hash_name'), 'skins_collections', ['market_hash_name'], unique=False)
    op.create_foreign_key(None, 'skins_collections', 'skins', ['market_hash_name'], ['market_hash_name'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('skins_collections', 'short_name')
    op.drop_column('users_likes_skins', 'short_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_likes_skins', sa.Column('short_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('skins_collections', sa.Column('short_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'skins_collections', type_='foreignkey')
    op.drop_index(op.f('ix_skins_collections_market_hash_name'), table_name='skins_collections')
    op.drop_column('skins_collections', 'market_hash_name')
    # ### end Alembic commands ###
