"""last update in skins price info

Revision ID: e05bf75278f0
Revises: 82bc74b7e842
Create Date: 2025-08-03 00:10:23.164922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e05bf75278f0'
down_revision: Union[str, Sequence[str], None] = '82bc74b7e842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins_price_info', sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skins_price_info', 'last_update')
    # ### end Alembic commands ###
