"""empty message

Revision ID: e2af2cafa5a2
Revises: 
Create Date: 2025-07-06 13:02:59.495521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2af2cafa5a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skins',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('price_last_1_day', sa.Float(), nullable=True),
    sa.Column('price_last_30_day', sa.Float(), nullable=True),
    sa.Column('price_last_365_day', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('steam_id', sa.BigInteger(), nullable=False),
    sa.Column('steam_name', sa.String(), nullable=False),
    sa.Column('steam_avatar', sa.String(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_steam_id', 'users', ['steam_id'], unique=False)
    op.create_index('idx_telegram_id', 'users', ['telegram_id'], unique=False)
    op.create_table('skins_price_history',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('skin_name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skin_name'], ['skins.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index('idx_skin_history_name', 'skins_price_history', ['skin_name'], unique=False)
    op.create_index('idx_skin_history_timestamp', 'skins_price_history', ['timestamp'], unique=False)
    op.create_table('users_portfolio',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('skin_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('buy_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['skin_name'], ['skins.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index('idx_portfolio_skin_name', 'users_portfolio', ['skin_name'], unique=False)
    op.create_index('idx_portfolio_user_uuid', 'users_portfolio', ['user_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_portfolio_user_uuid', table_name='users_portfolio')
    op.drop_index('idx_portfolio_skin_name', table_name='users_portfolio')
    op.drop_table('users_portfolio')
    op.drop_index('idx_skin_history_timestamp', table_name='skins_price_history')
    op.drop_index('idx_skin_history_name', table_name='skins_price_history')
    op.drop_table('skins_price_history')
    op.drop_index('idx_telegram_id', table_name='users')
    op.drop_index('idx_steam_id', table_name='users')
    op.drop_table('users')
    op.drop_table('skins')
    # ### end Alembic commands ###
