"""add short_name in skins_collections

Revision ID: ea42d28da949
Revises: a02d227c7291
Create Date: 2025-11-12 12:13:09.941200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea42d28da949'
down_revision: Union[str, Sequence[str], None] = 'a02d227c7291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins_collections', sa.Column('short_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skins_collections', 'short_name')
    # ### end Alembic commands ###
